WHOIGit/ooicgsn-roundabout

- roundabout/search/views.py
- roundabout/static/js/form-search.js
- roundabout/templates/search/adv_search.html
In response to #67 
1. added button to search for "all items
2. added Old Serial Number back in
3. Removed search on Note (revision__note which was actually in part template), Added search on Detail instead
4. re-labeled and re-ordered search dropdown categories
5. bonus: more buttons which load results have spinners and can't be re-clicked
> PR in response to Search Feedback (Issue #67)

- roundabout/search/views.py
- roundabout/templates/search/_searchbar.html
- roundabout/templates/search/adv_search.html
(1) reordered and parametized instances of "Assembly Templates" and "
(2) removed erroneous search on detail which is a pass-through field for action-detail
(3) renamed Latest Action: Details to be labeled as Latest Action: Notes
see Search Feedback Issue #67
> PR-2 in response to Search Feedback

- compose/local/django/Dockerfile
Docker-build fails due to old pip version. Added pip upgrade logic to Dockerfile.
> added pip upgrade statement prior to requirements install

- roundabout/search/tables.py
- roundabout/search/views.py
> Issue #78 bugfix - inconsistent part name search/display

- roundabout/configs_constants/models.py
- roundabout/exports/views.py
> PR for Issue #148 addressing Bulk Export of Calibs with Configs+Constants

- roundabout/exports/views.py
- roundabout/search/views.py
> Bugfix for bad Config search results

- compose/local/tests/Dockerfile
In Dockerfile for Automated Tests service, installed npm and  removed unnecessary version check for npm.
> Fix Issue #163

- roundabout/search/tables.py
> Part-search UDF-column filter expected a list, not a string

- roundabout/exports/views.py
> bugfix 174: bulk export of cruise csv - removed trailing comma

- roundabout/templates/exports/home.html
> interface edit #175: hide bulk-export buttons that include CCCs

- roundabout/assemblies/views.py
- roundabout/configs_constants/forms.py
- roundabout/configs_constants/views.py
- roundabout/templates/assemblies/ajax_assemblypart_detail.html
- roundabout/templates/configs_constants/config_default_detail.html
- roundabout/templates/configs_constants/config_name_detail.html
- roundabout/templates/inventory/ajax_inventory_detail.html
- roundabout/templates/parts/ajax_part_detail.html
> Enable Configs/Consts for Electrical Parts

- roundabout/search/tables.py
- roundabout/search/views.py
bugfix for issue #113 
(1) CCC searchbar reviewer+approver
(2) conf/const Type search results column
> hotfix-113 

- roundabout/configs_constants/models.py
- roundabout/templates/configs_constants/configs_detail.html
- roundabout/templates/configs_constants/constants_detail.html
> Modify Deployment date retrieval from Config and Constant Events

- roundabout/exports/views.py
Export fixes for issue #206 following changes made by Mario in commit #221
> hotfix for issue #206 (1.5.1)

- roundabout/search/views.py
> hotfix for #226 Search-Build-prefetch_related-location error

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/ooi_ci_tools/views.py
- roundabout/templates/ooi_ci_tools/import_tool.html
> Calibration validation errors, multiple simultaneous upload types hotfix

- roundabout/ooi_ci_tools/forms.py
- roundabout/templates/calibrations/part_calname_form.html
- roundabout/templates/configs_constants/part_confname_form.html
> Cancel button for CCC Name removal modal, Manufacturer Serial Number validation, Duplicate Vessel validation

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Manufacturer Serial Number Validation / Parsing Hotfix

- roundabout/ooi_ci_tools/forms.py
> Inventory MSN validation, Calibration Name generation, Coefficient Value set type

- roundabout/admintools/views.py
- roundabout/exports/views.py
- roundabout/inventory/urls.py
- roundabout/search/urls.py
- roundabout/search/user_search.py
- roundabout/search/views.py
- roundabout/static/js/form-search.js
- roundabout/templates/search/ReviewerApproverSearch.html
- roundabout/templates/search/_search-model-dropdown_button.html
- roundabout/templates/search/_searchbar.html
- roundabout/templates/search/adv_search.html
Several updates in this one.
#199 new single-user search across all CCCs and Actions
#219 searches on users match both usernames and names
#220 correct date searching
#234 #235 search and export skips over "disabled" CCCs
#275 ability to search on null and empty fields
> PR: Search dev for 1.6.2

- roundabout/calibrations/tasks.py
- roundabout/calibrations/views.py
- roundabout/configs_constants/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Calibration CSV Action History, Event-checking Celery-task, Calibration Name autogeneration reversion 

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/templates/calibrations/part_calname_form.html
- roundabout/templates/configs_constants/part_confname_form.html
> Importer, CCC Name modal hotfixes

- roundabout/ooi_ci_tools/forms.py
- roundabout/templates/calibrations/cal_name_detail.html
- roundabout/templates/calibrations/event_calname_delete.html
- roundabout/templates/configs_constants/config_name_detail.html
- roundabout/templates/configs_constants/event_confname_delete.html
> CCC Name post-deletion, Config Event generation hotfixes

- roundabout/search/user_search.py
- roundabout/search/views.py
- roundabout/static/js/form-search.js
> Hotfixes for 1.6.3 Search

- roundabout/templates/calibrations/cal_name_detail.html
- roundabout/templates/calibrations/part_calname_form.html
- roundabout/templates/configs_constants/config_name_detail.html
- roundabout/templates/configs_constants/part_confname_form.html
> CCC Name Custom Warning Modal

- roundabout/builds/views_deployments.py
- roundabout/search/views.py
> Improvement to Action history entries involving Cruises

- roundabout/templates/calibrations/part_calname_form.html
- roundabout/templates/configs_constants/part_confname_form.html
> Hotfix for Firefox row-duplication

- tests/CalibrationsCoefs.js
- tests/ConstantsConfigs.js
Update Automated Tests for Constants & Configs and Calibration recent screen changes, pull request 316.
> Update CCC Screen Changes

- roundabout/inventory/views.py
- roundabout/templates/exports/home.html
> hotfix #322

- roundabout/search/tables.py
Search/Actions hotfix for #330
I think this was due to a merge-conflict mistake at some point.
> hotfix #330

- roundabout/parts/forms.py
Added part custom field Dropdown Field form clause to fix #167
> bugfix #167

- tests/AddBuilds.js
- tests/CalibrationsCoefs.js
- tests/ConstantsConfigs.js
@cahearn requested a test be added for verify that the Assembly Template link on a Build screen points to the correct Assembly Template. Added test to AddBuilds.js.
> Add Test: Verify Build Assembly Template Link

- roundabout/search/tables.py
- roundabout/search/user_search.py
- roundabout/search/views.py
> search field truncation bugfix

- roundabout/builds/forms.py
- roundabout/calibrations/utils.py
- roundabout/calibrations/views.py
- roundabout/templates/builds/ajax_build_detail.html
> Hotfixes for Deployment Review

- roundabout/assemblies/views.py
- roundabout/builds/views.py
- roundabout/inventory/utils.py
- roundabout/inventory/views.py
- roundabout/parts/views.py
- roundabout/templates/assemblies/assembly_tree_parts.html
- roundabout/templates/builds/ajax_build_navtree.html
- roundabout/templates/builds/build_tree_assembly.html
- roundabout/templates/inventory/ajax_inventory_navtree.html
- roundabout/templates/inventory/inventory_tree_unassigned.html
- roundabout/templates/parts/ajax_part_navtree.html
- roundabout/templates/parts/part_tree.html
- roundabout/templates/parts/part_tree_parts.html
> Navtree User-Reviewer Optimisation

- roundabout/ooi_ci_tools/tasks.py
- roundabout/search/views.py
> small bugfixes

- config/settings/base.py
- roundabout/calibrations/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/models.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/ooi_ci_tools/views.py
- roundabout/templates/ooi_ci_tools/bulkupload_edit.html
> initial bulkupload event action history, approval logic

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/templates/calibrations/part_calname_form.html
- roundabout/templates/configs_constants/part_confname_form.html
> Bulk upload / Vessel CSV parse bugfixes, CCC Name general edit warnings for existing Event records

- roundabout/inventory/utils.py
- roundabout/inventory/views.py
- roundabout/ooi_ci_tools/views.py
- roundabout/templates/inventory/ajax_inventory_detail.html
- roundabout/templates/ooi_ci_tools/bulkupload_detail.html
> Bulk Upload Action History update, Filename context collapsible 

- roundabout/tags/forms.py
- roundabout/templates/assemblies/ajax_assemblypart_detail.html
- roundabout/templates/assemblies/reference_designator_detail.html
- roundabout/templates/configs_constants/config_default_detail.html
assembly part bugfixes for tab panel not displaying right + better form field validating for tags
> Assembly Parts bugfixes

- roundabout/inventory/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/templates/inventory/ajax_inventory_detail.html
- roundabout/templates/inventory/inventory_tree_unassigned.html
#478 #479 #483 
Event details tabs from the Inventory Details page now indicate if the logged-in User is a Reviewer for any Event within the tab.
Inventory Navtree items now indicate if the logged-in User has Comments with Replies.
Bulk Upload CSV Import now throws validation error if no matching Inventory serial numbers found,.
> Review, Comment Badges, Bulk Upload fix

- roundabout/calibrations/utils.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/ooi_ci_tools/views.py
- roundabout/templates/builds/build_tree_assembly.html
- roundabout/templates/ooi_ci_tools/action_comment_detail.html
> Bulk Import, Approval, Comment enhancements and bugfixes

- roundabout/inventory/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/templates/inventory/ajax_inventory_detail.html
- roundabout/templates/ooi_ci_tools/bulkupload_detail.html
- roundabout/templates/ooi_ci_tools/import_tool.html
> Part, Inventory Bulk Upload UI/Back-end fixes

- roundabout/ooi_ci_tools/forms.py
> CCC Import Validation fixes/enhancements

- roundabout/calibrations/forms.py
- roundabout/inventory/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/static/js/project.js
- roundabout/templates/inventory/ajax_inventory_detail.html
> UI / Import Validation Fixes

- roundabout/templates/cruises/vessel_list.html
Add Vessel button was accidentally deleted, and has been readded to Vessel list.
> Add Vessel hotfix

- roundabout/cruises/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/templates/assemblies/assembly_tree_parts.html
- roundabout/templates/builds/ajax_build_navtree.html
- roundabout/templates/builds/build_tree_assembly.html
- roundabout/templates/cruises/ajax_cruise_navtree.html
- roundabout/templates/inventory/ajax_inventory_navtree.html
- roundabout/templates/inventory/inventory_tree_unassigned.html
- roundabout/templates/parts/part_tree.html
- roundabout/templates/parts/part_tree_parts.html
> Cruise/Vessel Event, Review badge, Bulk Asset Inventory generation, Deployment Assembly Revision fixes

- roundabout/calibrations/utils.py
- roundabout/calibrations/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Import and Approval fixes

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/templates/cruises/ajax_cruise_detail.html
> Deployment/RefDes Import, Cruise Approval UI hotfixes

- roundabout/builds/views.py
- roundabout/inventory/models.py
- roundabout/inventory/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/ooi_ci_tools/views.py
- roundabout/templates/inventory/ajax_inventory_detail.html
- roundabout/templates/inventory/inventory_deployment_detail.html
- roundabout/templates/ooi_ci_tools/import_tool.html
#553 #446 #512 #554 #558 #556 #546 #548 #557
> Import Backend, Inventory/Build UI fixes

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
- roundabout/templates/inventory/ajax_inventory_detail.html
> inventory ui, deployment task, bulk validation fixes

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Deployment Import: assembly, assembly revision, comment skip fixes

- roundabout/calibrations/utils.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> deployment import and cruise event bugfixes

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Deployment Import: AssemblyPart Duplication Hotfix

- roundabout/ooi_ci_tools/tasks.py
> Deployment Import AssemblyPart duplication hotfix

- roundabout/admintools/views.py
- roundabout/templates/admintools/import_tempimport_detail.html
> Bulk Upload: Inventory Location Change: Deployed Build hotfix

- roundabout/admintools/views.py
> modify location change for non-deployed build inventory

- roundabout/admintools/views.py
> hotfix for location change

- roundabout/admintools/views.py
> Bulk Upload Deployed Build Location Hotfix

- roundabout/admintools/views.py
> hotfix for bul upload inv on deployed build location change

- roundabout/admintools/views.py
- roundabout/ooi_ci_tools/tasks.py
> Bulk inventory hotfix

- roundabout/admintools/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Bulk Import/Upload fixins

- roundabout/admintools/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Bulk Import/Upload hotfixes 

- roundabout/admintools/views.py
- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Bulk upload custom field hotfix

- roundabout/admintools/views.py
- roundabout/ooi_ci_tools/forms.py
> Bulk Upload Hotfixes

- roundabout/ooi_ci_tools/tasks.py
> Bulk Upload Import hotfix

- roundabout/admintools/forms.py
> Bulk Upload Required Field Validation

- roundabout/admintools/forms.py
> Bulk Upload validation hotfix

- roundabout/core/updaters.py
- roundabout/cruises/views.py
> cruise event updater hotfix

- roundabout/templates/cruises/ajax_cruise_detail.html
> modify cruise ui

- roundabout/exports/views.py
this patch fixes the reported deployment_depth value for Deployment csv exports.
> ci deployment csv export depth-patch

- roundabout/ooi_ci_tools/forms.py
> Deployment CSV Location Validation Hotfix

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Bulk Import Optimization

- roundabout/ooi_ci_tools/tasks.py
- roundabout/templates/cruises/vessel_list.html
When importing Cruises, Vessel Reviewers now behave like Cruise Reviewers. Vessel detail page should load without Vessels in the system.
> Vessels Hotfix

- roundabout/ooi_ci_tools/tasks.py
> initial calibration import optimization, vessel event hotfix

- .github/workflows/zap-publish-image-rdb.yml
- compose/local/tests/Dockerfile
- tests/RunAllTests-Chrome-Linux.bat
Updated Nodejs to version 16.x in Github Actions and Dockerfile
> Automated tests: update Nodejs Version

- roundabout/ooi_ci_tools/tasks.py
> remove atomic transaction decorator from bulk import proc

- roundabout/ooi_ci_tools/tasks.py
> Bulk CSV Import: Inventory Deadlock Hotfix

- roundabout/ooi_ci_tools/forms.py
- roundabout/ooi_ci_tools/tasks.py
> Deployment Bulk Import: Reference Designator validation and parsing hotfix

- roundabout/core/updaters.py
Update to roundabout.core.updaters function to generate Reference Designators from AssemblyPart Configuration Default values.
> AssemblyPart Reference Designator Update Hotfix

- roundabout/ooi_ci_tools/tasks.py
> bulk deployment inventorydeployment hotfix

- roundabout/core/updaters.py
New function _update_vessel_events() generates VesselEvents for Vessels.
> Mario dev 1.7.0

- compose/local/tests/Dockerfile
- tests/AddBuilds.js
- tests/AddEditInventory.js
- tests/AdminUser.js
- tests/Buildup-Docker.bat
- tests/CalibrationsCoefs.js
- tests/ConstantsConfigs.js
- tests/ImportExportInventory.js
- tests/RunAllTests-Chrome-Linux.bat
- tests/UploadCsv.js
Add Build Snapshots test, fix depreciated Selenium by.tagName("Body") calls and fix depreciated node.js install.
> Automated tests - add test for Build Snapshots
